micronaut:
  banner: true
  application:
    name: account-holder-identity-documents
  server:
    port: 8074
    multipart:
      enabled: true
      max-file-size: 20971520 # 20 * 1024 * 1024 = 20MB

  object-storage:
    aws:
      account-holder-identity-document:
        bucket: ${AWS_S3_ACCOUNT_HOLDER_IDENTITY_DOCUMENTS_BUCKET_NAME}

aws:
  access-key-id: ${AWS_ACCESS_KEY_ID}
  secret-key: ${AWS_SECRET_ACCESS_KEY}
  region: ${AWS_DEFAULT_REGION}