aws:
  access-key-id: 'test'
  secret-key: 'test'
  region: 'us-east-1'
  services:
    s3:
      endpoint-override: 'http://127.0.0.1:4566'

micronaut:
  object-storage:
    aws:
      account-holder-identity-documents:
        bucket: 'jcondotta-account-holder-identity-documents-localstack'
  openapi:
    filename: recipients-swagger-spec
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**